# azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # Change to your main branch name

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Specify the Node.js version you want to use
    checkLatest: true

# - script: |
#     npm install -g htmlhint  # Install htmlhint globally
#   displayName: 'Install htmlhint'

# - script: |
#     htmlhint **/*.html  # Lint all HTML files in the repository
#   displayName: 'Lint HTML files'
